#!/usr/bin/env python
# -*- coding: utf-8 -*-

from PySide6.QtCore import Qt
from PySide6.QtWidgets import QDialog, QComboBox


class CommandDialog(QDialog):
    CODE_DESCRIBE = {
        0x00: '區塊編號 - BLOCK',
        0x01: '區塊結束符 - STOP',
        0x02: '條件判斷 - IF',
        0x03: '條件判斷 - ANY',
        0x04: '條件判斷 - THEN',
        0x05: '條件判斷 - ELSE',
        0x06: '條件判斷 - ENDIF',
        0x08: '流程控制 - GOTO',
        0x09: '流程控制 - RUN',
        0x0A: '流程控制 - RETURN',
        0x0B: '數據載入 - LOAD',
        0x0C: '事件系統 - 觸發全局事件',
        0x0D: '事件系統 - 觸發場景事件',
        0x0E: '事件系統 - 操作場景點數',
        0x0F: '事件系統 - 操作全局點數',
        0x10: '事件系統 - 判斷全局事件',
        0x11: '事件系統 - 判斷場景事件',
        0x12: '事件系統 - 場景點數比較',
        0x13: '事件系統 - 全局點數比較',
        0x14: '條件表達式 - 真實係',
        0x15: '條件表達式 - 超級係',
        0x16: '條件表達式 - 返回否',
        0x17: '場景文本 - 普通會話',
        0x18: '場景文本 - 變量會話',
        0x19: '場景文本 - 語音會話',
        0x1A: '場景文本 - 最終話不同主角對戰BOSS切換',
        0x1B: '場景文本 - 最終話主角對戰BOSS會話',
        0x1C: '場景文本 - 播放音樂會話',
        0x1D: '場景文本 - 停止音樂會話',
        0x1E: '場景文本 - 勝利與失敗條件',
        0x1F: '場景文本 - 會話選單',
        0x21: '場景文本 - 判斷選擇項',
        0x22: '場景控制 - 勝利',
        0x23: '場景控制 - 失敗',
        0x24: '場景控制 - 跳轉場景',
        0x25: '場景控制 - 判斷回合數',
        0x26: '場景控制 - 設定場景音樂',
        0x27: '場景控制 - 播放指定音樂',
        0x28: '場景控制 - 場景音樂復位',
        0x29: '場景控制 - 播放音效',
        0x2A: '場景控制 - 播放動畫',
        0x2B: '場景控制 - 靜止時間',
        0x2C: '出擊控制 - 列表隊出擊',
        0x2D: '出擊控制 - 列表隊出擊到人物相對坐標',
        0x2F: '出擊控制 - 列表隊再出擊',
        0x30: '機庫控制 - 機庫打開',
        0x31: '機庫控制 - 機庫關閉',
        0x32: '機庫控制 - 增加機體',
        0x33: '機庫控制 - 機體離隊',
        0x34: '機庫控制 - 機體歸隊',
        0x35: '機庫控制 - 刪除機體',
        0x36: '機庫控制 - 替換機體',
        0x37: '機庫控制 - 增加機師',
        0x38: '機庫控制 - 機師離隊',
        0x39: '機庫控制 - 機師歸隊',
        0x3A: '機庫控制 - 刪除機師',
        0x3B: '機庫控制 - 替換機師',
        0x3C: '未知',
        0x3D: '機庫控制 - 增加機體機師或强制換乘',
        0x3E: '機庫控制 - 機師分流',
        0x3F: '機庫控制 - 機體合流',
        0x40: '機庫控制 - 機師合流',
        0x41: '機庫控制 - 機體歸隊',
        0x42: '機庫控制 - 機師離開',
        0x43: '機庫控制 - 强制換乘',
        0x44: '機庫控制 - 換乘空機體',
        0x45: '機庫控制 - 取消機師乘坐',
        0x46: '機庫控制 - 增加機體',
        0x47: 'h',
        0x48: 'hh',
        0x49: 'h',
        0x4A: 'h',
        0x4B: 'h',
        0x4E: 'h',
        0x4F: '',
        0x50: '',
        0x51: 'hhh',
        0x52: 'hhhh',
        0x54: 'hhh',
        0x55: 'hhhh',
        0x57: 'hh',
        0x58: 'hhh',
        0x5A: 'hhh',
        0x5B: 'hhh',
        0x5C: 'hh',
        0x5D: 'hh',
        0x5E: 'hh',
        0x5F: 'h',
        0x60: 'hh',
        0x61: 'h',
        0x62: 'hh',
        0x63: 'h',
        0x64: 'l',
        0x65: 'h',
        0x66: 'h',
        0x67: 'hhh',
        0x68: 'hhhh',
        0x69: 'hbbhh',
        0x6A: 'hh',
        0x6B: 'hhh',
        0x6C: 'hhh',
        0x6E: 'h',
        0x6F: 'h',
        0x70: 'bb',
        0x71: 'h',
        0x72: 'h',
        0x73: 'h',
        0x74: 'hhhhh',
        0x75: 'hh',
        0x77: 'hh',
        0x78: 'h',
        0x79: 'hhh',
        0x7A: 'hhh',
        0x7B: 'hhh',
        0x7C: 'hhhhh',
        0x7D: 'hhhhh',
        0x7E: 'hhhhh',
        0x80: 'hhhhh',
        0x81: 'hhhhh',
        0x82: 'hhh',
        0x83: 'hbbh',
        0x84: 'hh',
        0x85: 'hh',
        0x86: 'hh',
        0x87: '',
        0x88: 'hh',
        0x89: 'hh',
        0x8B: 'hh',
        0x8C: 'hhh',
        0x8D: 'hh',
        0x8E: 'h',
        0x8F: 'h',
        0x90: 'hhh',
        0x91: 'bbhh',
        0x92: 'hhhhh',
        0x93: 'hbbhhh',
        0x94: 'bbhhhh',
        0x96: 'hhhhhhhhhh',
        0x97: 'bbhhhhhhhhh',
        0x98: 'hbbhhhhhhhh',
        0x99: '',
        0x9A: 'hh',
        0x9B: 'hh',
        0x9C: 'hh',
        0x9D: 'bbh',
        0x9E: 'hh',
        0x9F: 'h',
        0xA0: 'bb',
        0xA1: 'h',
        0xA2: 'h',
        0xA3: 'h',
        0xA4: 'h',
        0xA5: 'hh',
        0xA6: 'h',
        0xA7: 'h',
        0xA8: 'hhhh',
        0xA9: 'hh',
        0xAA: 'h',
        0xAB: 'hh',
        0xAC: 'hbb',
        0xAD: 'hh',
        0xAE: 'hbb',
        0xAF: 'hh',
        0xB0: 'hbb',
        0xB1: 'h',
        0xB2: 'bb',
        0xB3: 'h',
        0xB4: 'h',
        0xB5: 'h',
        0xB6: 'hh',
        0xB7: 'h',
        0xB8: 'bb',
        0xB9: '',
        0xBA: 'hhh',
        0xBB: 'hhhh',
    }

    def __init__(self, parent, command: dict = None):
        super(CommandDialog, self).__init__(parent, f=Qt.Dialog)
        self.command = command if command else {'Pos': 0x0, 'Code': 0x0, 'Count': 0x1, 'Param': list(), 'Data': ''}
        self.code_combo = self.code_combo

    def code_combo(self):
        combo = QComboBox(self)
        return combo
