[project]
name = "SRW_Alpha"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fonttools>=4.61.0",
    "pyside6-fluent-widgets[full]>=1.9.2",
    "pyside6-stubs>=6.7.3.0",
]

[[tool.uv.index]]
name = "tuna"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"

[[tool.uv.index]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"