[project]
name = "SRW_Alpha"
version = "0.3.0"
description = "Super Robot Wars α ROM Editor — 超级机器人大战α ROM 编辑器"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fonttools>=4.61.0",
    "pyside6-fluent-widgets[full]>=1.9.2",
    "pyside6-stubs>=6.7.3.0",
    "setuptools>=83.0.0",
]

[[tool.uv.index]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
