from typing import Any

from PySide6.QtCore import QObject


class EnumData(QObject):
    def __init__(self) -> None:
        super().__init__(parent=None)
        self.SCENARIO = {
            0x00: ("[00]", self.tr("Unified"), self.tr("Stage 0"), self.tr("Prologue")),  # '共通', '第０話', 'プロローグ'),
            0x01: ("[01]", self.tr("Super"), self.tr("Stage 1"), self.tr("Cockpit of Steel")),  # 'スーパー系', '第１話', '鋼鉄のコクピット'),
            0x02: ("[02]", self.tr("Super"), self.tr("Stage 2"), self.tr("Desperate Situation For Mazinger Z")),  # 'スーパー系', '第２話', 'マジンガーＺ絶体絶命'),
            0x03: ("[03]", self.tr("Super"), self.tr("Stage 3"), self.tr("Getter Team, Launch!")),  # 'スーパー系', '第３話', 'ゲッターチーム出撃せよ！'),
            0x04: ("[04]", self.tr("Super"), self.tr("Stage 4"), self.tr("Zeon's Second Coming")),  # 'スーパー系', '第４話', 'ジオン再臨'),
            0x05: ("[05]", self.tr("Super"), self.tr("Stage 5"), self.tr("Secret Numbers")),  # 'スーパー系', '第５話', 'シークレット・ナンバーズ'),
            0x06: ("[06]", self.tr("Super"), self.tr("Stage 6"), self.tr("The Order To Shoot Down The Argama")),  # 'スーパー系', '第６話', 'アーガマ撃墜命令'),
            0x07: ("[07]", self.tr("Real"), self.tr("Stage 1"), self.tr("Vanishing Trooper")),  # 'リアル系', '第１話', 'バニシング・トルーパー'),
            0x08: ("[08]", self.tr("Real"), self.tr("Stage 2"), self.tr("Black Gundam")),  # 'リアル系', '第２話', '黒いガンダム'),
            0x09: ("[09]", self.tr("Real"), self.tr("Stage 3"), self.tr("Rescue The White Base")),  # 'リアル系', '第３話', 'ホワイトベース救出'),
            0x0A: ("[0A]", self.tr("Real"), self.tr("Stage 4"), self.tr("The Man Called Death")),  # 'リアル系', '第４話', '死神と呼ばれたＧ'),
            0x0B: ("[0B]", self.tr("Real"), self.tr("Stage 5"), self.tr("The Ghosts Of Zeon")),  # 'リアル系', '第５話', 'ジオンの亡霊'),
            0x0C: ("[0C]", self.tr("Real"), self.tr("Stage 6"), self.tr("Showdown At The Far East Base")),  # 'リアル系', '第６話', '対決、極東基地'),
            0x0D: ("[0D]", self.tr("Unified"), self.tr("Stage 7"), self.tr("Let's Combine!")),  # '共通', '第７話', 'レッツ！コンバイン'),
            0x0E: ("[0E]", self.tr("Unified"), self.tr("Stage 8"), self.tr("Sally Forth! Its Name Is Giant Robo")),  # '共通', '第８話', '出撃！その名はジャイアント・ロボ'),
            0x0F: ("[0F]", self.tr("Super"), self.tr("Stage 9"), self.tr("He Who Summons The Winds")),  # 'スーパー系', '第９話', '風を呼ぶ者'),
            0x10: ("[10]", self.tr("Real"), self.tr("Stage 9"), self.tr("The Unknown Calamity")),  # 'リアル系', '第９話', '未知なる災い'),
            0x11: ("[11]", self.tr("Jaburo"), self.tr("Stage 10"), self.tr("Amuro Again")),  # 'ジャブロー', '第１０話', 'アムロ再び'),
            0x12: ("[12]", self.tr("Jaburo"), self.tr("Stage 11"), self.tr("The White Mobile Suit")),  # 'ジャブロー', '第１１話', '白いモビルスーツ'),
            0x13: ("[13]", self.tr("Jaburo"), self.tr("Stage 12"), self.tr("For Whom We Fight")),  # 'ジャブロー', '第１２話', '戦いは誰のために'),
            0x14: ("[14]", self.tr("Jaburo"), self.tr("Stage 13"), self.tr("The Gundam That Had Wings")),  # 'ジャブロー', '第１３話', '翼を持ったガンダム'),
            0x15: ("[15]", self.tr("South Ataria"), self.tr("Stage 10"), self.tr("Awaken, Brave One")),  # '南アタリア島', '第１０話', '目覚めよ、勇者'),
            0x16: ("[16]", self.tr("South Ataria"), self.tr("Stage 11"), self.tr("Gundam Theft")),  # '南アタリア島', '第１１話', 'ガンダム強奪'),
            0x17: ("[17]", self.tr("South Ataria"), self.tr("Stage 12"), self.tr("A Man Of Ambitions")),  # '南アタリア島', '第１２話', '野望の男'),
            0x18: ("[18]", self.tr("South Ataria"), self.tr("Stage 13"), self.tr("The Shooting Star She Saw")),  # '南アタリア島', '第１３話', '少女が見た流星'),
            0x19: ("[19]", self.tr("Unified"), self.tr("Stage 14"), self.tr("A Promise With Father")),  # '共通', '第１４話', '父との約束'),
            0x1A: ("[1A]", self.tr("Unified"), self.tr("Stage 15"), self.tr("Angel Attack")),  # '共通', '第１５話', '使徒、襲来'),
            0x1B: ("[1B]", self.tr("Unified"), self.tr("Stage 16"), self.tr("Roar, EVA Unit-01")),  # '共通', '第１６話', '咆哮、ＥＶＡ初号機'),
            0x1C: ("[1C]", self.tr("Unified"), self.tr("Stage 17"), self.tr("GR vs. GR2")),  # '共通', '第１７話', 'ＧＲ対ＧＲ２'),
            0x1D: ("[1D]", self.tr("Real"), self.tr("Stage 18"), self.tr("The Sign Of Zeta")),  # 'リアル系', '第１８話', 'ゼータの鼓動'),
            0x1E: ("[1E]", self.tr("Real"), self.tr("Stage 19"), self.tr("His Second Engagement")),  # 'リアル系', '第１９話', '第二次直上会戦'),
            0x1F: ("[1F]", self.tr("Super"), self.tr("Stage 18"), self.tr("With A Red Flash, Fly To The Sky, Mazinger")),  # 'スーパー系', '第１８話', '紅い稲妻 空飛ぶマジンガー'),
            0x20: ("[20]", self.tr("Super"), self.tr("Stage 19"), self.tr("Clash! Getter Robo vs. Getter Robo G")),  # 'スーパー系', '第１９話', '激突！ゲッターロボＶＳゲッターロボＧ'),
            0x21: ("[21]", self.tr("Unified"), self.tr("Stage 20 Screen"), self.tr("A Decisive Battle In New Tokyo 2")),  # '共通', '第２０話幕前', '決戦、第２新東京市'),
            0x22: ("[22]", self.tr("Unified"), self.tr("Stage 20"), self.tr("A Decisive Battle In New Tokyo 2")),  # '共通', '第２０話', '決戦、第２新東京市'),
            0x23: ("[23]", self.tr("EVA Unit-02"), self.tr("Stage 21 Screen"), self.tr("Aura Battlers")),  # 'ＥＶＡ弐号機', '第２１話幕前', '聖戦士たち'),
            0x24: ("[24]", self.tr("EVA Unit-02"), self.tr("Stage 21"), self.tr("Aura Battlers")),  # 'ＥＶＡ弐号機', '第２１話', '聖戦士たち'),
            0x25: ("[25]", self.tr("EVA Unit-02"), self.tr("Stage 22"), self.tr("Elle's Aura")),  # 'ＥＶＡ弐号機', '第２２話', 'エレの霊力'),
            0x26: ("[24]", self.tr("EVA Unit-02"), self.tr("Stage 23"), self.tr("The Land Of Na's Queen")),  # 'ＥＶＡ弐号機', '第２３話', 'ナの国の女王'),
            0x27: ("[25]", self.tr("EVA Unit-02"), self.tr("Stage 24"), self.tr("The Aura Road")),  # 'ＥＶＡ弐号機', '第２４話', 'オーラロード'),
            0x28: ("[26]", self.tr("EVA Unit-02"), self.tr("Stage 25"), self.tr("The Skies Of Tokyo")),  # 'ＥＶＡ弐号機', '第２５話', '東京上空'),
            0x29: ("[27]", self.tr("Far East Sector"), self.tr("Stage 21"), self.tr("Beyond Beast, Beyond Man, Become God's Warrior")),  # '極東基地', '第２１話', '獣を超え、人を超え、いでよ神の戦士'),
            0x2A: ("[28]", self.tr("Far East Sector"), self.tr("Stage 22"), self.tr("Into The Sea Of Battle")),  # '極東基地', '第２２話', '戦いの海へ'),
            0x2B: ("[29]", self.tr("Far East Sector"), self.tr("Stage 23 Act 1"), self.tr("Mazinger Z vs. Ankoku Dai-Shogun")),  # '極東基地', '第２３話第１幕', 'マジンガーＺ対暗黒大将軍'),
            0x2C: ("[29]", self.tr("Far East Sector"), self.tr("Stage 23 Act 2"), self.tr("Mazinger Z vs. Ankoku Dai-Shogun")),  # '極東基地', '第２３話第２幕', 'マジンガーＺ対暗黒大将軍'),
            0x2D: ("[2A]", self.tr("Far East Sector"), self.tr("Stage 24"), self.tr("Voltes, Back From The Ashes")),  # '極東基地', '第２４話', 'ボルテス起死回生'),
            0x2E: ("[2B]", self.tr("Far East Sector"), self.tr("Stage 25"), self.tr("The Devil Sharkin's Battle")),  # '極東基地', '第２５話', 'シャーキン悪魔の戦い'),
            0x2F: ("[2C]", self.tr("League Millitaire"), self.tr("Stage 21"), self.tr("Hong Kong City")),  # 'リガ・ミリティア', '第２１話', 'ホンコン・シティ'),
            0x30: ("[2D]", self.tr("League Millitaire"), self.tr("Stage 22"), self.tr("Gundam, Go To The Sea Of Stars")),  # 'リガ・ミリティア', '第２２話', 'ガンダム、星の海へ'),
            0x31: ("[2E]", self.tr("League Millitaire"), self.tr("Stage 23"), self.tr("Startup, Double Zeta")),  # 'リガ・ミリティア', '第２３話', '始動ダブルゼータ'),
            0x32: ("[2F]", self.tr("League Millitaire"), self.tr("Stage 24"), self.tr("The Nightmare Of Solomon")),  # 'リガ・ミリティア', '第２４話', 'ソロモンの悪夢'),
            0x33: ("[30]", self.tr("League Millitaire"), self.tr("Stage 25"), self.tr("Crossbone Vanguard")),  # 'リガ・ミリティア', '第２５話', 'クロスボーン・バンガード'),
            0x34: ("[31]", self.tr("EVA Unit-02 / Far East Sector"), self.tr("Stage 26"), self.tr("The Red Evangelion")),  # 'ＥＶＡ弐号機／極東基地', '第２６話', '紅いエヴァンゲリオン'),
            0x35: ("[32]", self.tr("League Millitaire"), self.tr("Stage 26"), self.tr("Terror From The Sea")),  # 'リガ・ミリティア', '第２６話', '海からのマレビト'),
            0x36: ("[33]", self.tr("Unified"), self.tr("Stage 27"), self.tr("Machine Development")),  # '共通', '第２７話', 'マシン展開'),
            0x37: ("[34]", self.tr("2 EVAs"), self.tr("Stage 30"), self.tr("Moment And Heart Together")),  # 'ＥＶＡ２体同時攻撃', '第３０話', '瞬間、心重ねて'),
            0x38: ("[35]", self.tr("Shoot Down"), self.tr("Stage 31"), self.tr("Booby Trap")),  # '弾丸を撃ち落す', '第３１話', 'ブービー・トラップ'),
            0x39: ("[36]", self.tr("Shoot Down"), self.tr("Stage 32"), self.tr("Count Down")),  # '弾丸を撃ち落す', '第３２話', 'カウント・ダウン'),
            0x3A: ("[37]", self.tr("Shoot Down"), self.tr("Stage 33"), self.tr("Trans-Formation")),  # '弾丸を撃ち落す', '第３３話', 'トランス・フォーメーション'),
            0x3B: ("[38]", self.tr("Shoot Down"), self.tr("Stage 34"), self.tr("Hidden Bloodlust")),  # '弾丸を撃ち落す', '第３４話', '隠された殺意'),
            0x3C: ("[39]", self.tr("Shoot Down"), self.tr("Stage 35"), self.tr("Saturn Fight")),  # '弾丸を撃ち落す', '第３５話', 'サタン・ファイト'),
            0x3D: ("[3A]", self.tr("Shoot Down"), self.tr("Stage 36"), self.tr("Lynn Minmay")),  # '弾丸を撃ち落す', '第３６話', 'リン・ミンメイ'),
            0x3E: ("[3B]", self.tr("Shoot Down"), self.tr("Stage 37"), self.tr("The Jupitorians")),  # '弾丸を撃ち落す', '第３７話', 'ジュピトリアン'),
            0x3F: ("[3C]", self.tr("Shoot Down"), self.tr("Stage 38"), self.tr("The Queen Of The Empire")),  # '弾丸を撃ち落す', '第３８話', '帝国の女王'),
            0x40: ("[3D]", self.tr("Shoot Down"), self.tr("Stage 39"), self.tr("Prelude To The End")),  # '弾丸を撃ち落す', '第３９話', '終末への前奏曲'),
            0x41: ("[3E]", self.tr("Catch with EVA"), self.tr("Stage 31"), self.tr("The Value Of A Miracle")),  # 'ＥＶＡで受け止める', '第３１話', '奇跡の価値は'),
            0x42: ("[3F]", self.tr("Catch with EVA"), self.tr("Stage 32"), self.tr("Space Fold")),  # 'ＥＶＡで受け止める', '第３２話', 'スペース・フォールド'),
            0x43: ("[40]", self.tr("Catch with EVA"), self.tr("Stage 33"), self.tr("Armed Attack")),  # 'ＥＶＡで受け止める', '第３３話', 'アームド・アタック'),
            0x44: ("[41]", self.tr("Catch with EVA"), self.tr("Stage 34"), self.tr("An Encounter With Our Natural Enemies")),  # 'ＥＶＡで受け止める', '第３４話', '天敵との遭遇'),
            0x45: ("[42]", self.tr("Catch with EVA"), self.tr("Stage 35"), self.tr("Ingram's True Intentions")),  # 'ＥＶＡで受け止める', '第３５話', 'イングラムの真意'),
            0x46: ("[43]", self.tr("Catch with EVA"), self.tr("Stage 36"), self.tr("Miss Macross")),  # 'ＥＶＡで受け止める', '第３６話', 'ミス・マクロス'),
            0x47: ("[44]", self.tr("Catch with EVA"), self.tr("Stage 37"), self.tr("Fugitive From Jupiter")),  # 'ＥＶＡで受け止める', '第３７話', '木星からの逃亡者'),
            0x48: ("[45]", self.tr("Catch with EVA"), self.tr("Stage 38"), self.tr("The One Who Will Guide Humanity")),  # 'ＥＶＡで受け止める', '第３８話', '人類を導く者'),
            0x49: ("[46]", self.tr("Catch with EVA"), self.tr("Stage 39"), self.tr("First Contact")),  # 'ＥＶＡで受け止める', '第３９話', 'ファースト・コンタクト'),
            0x4A: ("[47]", self.tr("Unified"), self.tr("Stage 40"), self.tr("The Big Escape")),  # '共通', '第４０話', 'ビッグ・エスケープ'),
            0x4B: ("[48]", self.tr("Unified"), self.tr("Stage 41"), self.tr("Bye Bye Mars")),  # '共通', '第４１話', 'バイバイ・マルス'),
            0x4C: ("[49]", self.tr("Reinforce Jr"), self.tr("Stage 42"), self.tr("A Messenger From Axis")),  # 'リーンホースＪｒ．隊', '第４２話', 'アクシズからの使者'),
            0x4D: ("[4A]", self.tr("Reinforce Jr"), self.tr("Stage 43"), self.tr("Puru, Axis and...")),  # 'リーンホースＪｒ．隊', '第４３話', 'プルとアクシズと'),
            0x4E: ("[4B]", self.tr("Reinforce Jr"), self.tr("Stage 44"), self.tr("Leina's Blood")),  # 'リーンホースＪｒ．隊', '第４４話', 'リィナの血'),
            0x4F: ("[4C]", self.tr("Reinforce Jr"), self.tr("Stage 45"), self.tr("The Coming Of The Black Angel")),  # 'リーンホースＪｒ．隊', '第４５話', '漆黒の天使来たりて'),
            0x50: ("[4D]", self.tr("Gran-Garan"), self.tr("Stage 42"), self.tr("The Jupiter Ghost")),  # 'グラン・ガラン隊', '第４２話', 'ジュピター・ゴースト'),
            0x51: ("[4E]", self.tr("Gran-Garan"), self.tr("Stage 43"), self.tr("The Terrible Flower Blooming In Space")),  # 'グラン・ガラン隊', '第４３話', '宇宙に咲く妖花'),
            0x52: ("[4F]", self.tr("Gran-Garan"), self.tr("Stage 44"), self.tr("The Gundam Called Zero")),  # 'グラン・ガラン隊', '第４４話', 'ゼロと呼ばれたガンダム'),
            0x53: ("[50]", self.tr("Gran-Garan"), self.tr("Stage 45"), self.tr("Assault On The Final Safeguard")),  # 'グラン・ガラン隊', '第４５話', '強襲、阻止限界点'),
            0x54: ("[51]", self.tr("Goraon"), self.tr("Stage 42"), self.tr("Father, The Earth Is Near")),  # 'ゴラオン隊', '第４２話', '父よ地球は近い'),
            0x55: ("[52]", self.tr("Goraon"), self.tr("Stage 43"), self.tr("Within The Paralyzing Darkness")),  # 'ゴラオン隊', '第４３話', '静止した闇の中で'),
            0x56: ("[53]", self.tr("Goraon"), self.tr("Stage 44"), self.tr("The Red Haired Woman")),  # 'ゴラオン隊', '第４４話', '赤い髪の女'),
            0x57: ("[54]", self.tr("Goraon"), self.tr("Stage 45"), self.tr("A God, Or A Devil")),  # 'ゴラオン隊', '第４５話', '神か、悪魔か・・・'),
            0x58: ("[55]", self.tr("Real"), self.tr("Stage 46"), self.tr("The Third's Power")),  # 'リアル系', '第４６話', '第三の力'),
            0x59: ("[56]", self.tr("Super"), self.tr("Stage 46"), self.tr("The Dragon And The Tiger")),  # 'スーパー系', '第４６話', '龍と虎'),
            0x5A: ("[57]", self.tr("Unified"), self.tr("Stage 47"), self.tr("A Man's Fight")),  # '共通', '第４７話', '男の戦い'),
            0x5B: ("[58]", self.tr("Unified"), self.tr("Stage 50"), self.tr("Variable Formation")),  # '共通', '第５０話', 'ヴァリアブル・フォーメーション'),
            0x5C: ("[59]", self.tr("Gran-Garan"), self.tr("Stage 51"), self.tr("The Glass Kingdom")),  # 'グラン・ガラン隊', '第５１話', 'ガラスの王国'),
            0x5D: ("[5A]", self.tr("Ra-Cailum"), self.tr("Stage 51"), self.tr("Day Of Dakar")),  # 'ラー・カイラム隊', '第５１話', 'ダカールの日'),
            0x5E: ("[5B]", self.tr("Gran-Garan"), self.tr("Stage 52"), self.tr("Kingdom's Fall")),  # 'グラン・ガラン隊', '第５２話', '王国崩壊'),
            0x5F: ("[5C]", self.tr("Ra-Cailum"), self.tr("Stage 52"), self.tr("Vibrations")),  # 'ラー・カイラム隊', '第５２話', 'バイブレーション'),
            0x60: ("[5D]", self.tr("Goraon"), self.tr("Stage 54"), self.tr("Memories Taken To The Future")),  # 'ゴラオン隊', '第５４話', '思い出を未来へ'),
            0x61: ("[5E]", self.tr("Ra-Cailum"), self.tr("Stage 53"), self.tr("The Capture Of Solomon")),  # 'ラー・カイラム隊', '第５３話', 'ソロモン攻略戦'),
            0x62: ("[5F]", self.tr("Ra-Cailum"), self.tr("Stage 54"), self.tr("The Womens' Battlefield")),  # 'ラー・カイラム隊', '第５４話', '女たちの戦場'),
            0x63: ("[60]", self.tr("Ra-Cailum"), self.tr("Stage 55"), self.tr("The Oncoming Storm")),  # 'ラー・カイラム隊', '第５５話', '駆け抜ける嵐'),
            0x64: ("[61]", self.tr("Goraon"), self.tr("Stage 51"), self.tr("The Fall Of Baron Ashura")),  # 'ゴラオン隊', '第５１話', 'あしゅら男爵、散る'),
            0x65: ("[62]", self.tr("Goraon"), self.tr("Stage 52"), self.tr("The Demon Emperor")),  # 'ゴラオン隊', '第５２話', '魔神皇帝'),
            0x66: ("[63]", self.tr("Gran-Garan"), self.tr("Stage 53"), self.tr("Cross Fight")),  # 'グラン・ガラン隊', '第５３話', 'クロス・ファイト'),
            0x67: ("[64]", self.tr("Gran-Garan"), self.tr("Stage 54"), self.tr("Foreigners' Return")),  # 'グラン・ガラン隊', '第５４話', '異邦人たちの帰還'),
            0x68: ("[65]", self.tr("Goraon"), self.tr("Stage 53"), self.tr("Duel For The Earth")),  # 'ゴラオン隊', '第５３話', '地球を賭けた一騎討ち'),
            0x69: ("[66]", self.tr("Unified"), self.tr("Stage 56"), self.tr("The Phantom Of Zeon")),  # '共通', '第５６話', 'ジオンの幻像'),
            0x6A: ("[67]", self.tr("Goraon"), self.tr("Stage 55"), self.tr("The Cry Within Father's Breast!")),  # 'ゴラオン隊', '第５５話', '父の胸の中で泣け！'),
            0x6B: ("[68]", self.tr("Gran-Garan"), self.tr("Stage 55"), self.tr("Queen Relena")),  # 'グラン・ガラン隊', '第５５話', '女王リリーナ'),
            0x6C: ("[69]", self.tr("Unified"), self.tr("Stage 57 Screen"), self.tr("Above The Angel's Halo")),  # '共通', '第５７話第０幕', '天使の輪の上で'),
            0x6D: ("[69]", self.tr("Unified"), self.tr("Stage 57"), self.tr("Above The Angel's Halo")),  # '共通', '第５７話', '天使の輪の上で'),
            0x6E: ("[6A]", self.tr("Axis"), self.tr("Stage 58"), self.tr("The Temptation Of The Land Of God")),  # 'アクシズ', '第５８話', '神の国への誘惑'),
            0x6F: ("[6B]", self.tr("Axis"), self.tr("Stage 59"), self.tr("Cross Target")),  # 'アクシズ', '第５９話', 'クロス・ターゲット'),
            0x70: ("[6C]", self.tr("Axis"), self.tr("Stage 60"), self.tr("Warriors, Again")),  # 'アクシズ', '第６０話', '戦士、再び・・・'),
            0x71: ("[6D]", self.tr("Angel Halo"), self.tr("Stage 58"), self.tr("Blessings Upon The Winner And Loser")),  # 'エンジェル・ハイロゥ', '第５８話', '勝者と敗者に祝福を'),
            0x72: ("[6E]", self.tr("Angel Halo"), self.tr("Stage 59"), self.tr("At Least, To Be Human")),  # 'エンジェル・ハイロゥ', '第５９話', 'せめて、人間らしく'),
            0x73: ("[6F]", self.tr("Angel Halo"), self.tr("Stage 60"), self.tr("The Final Messenger")),  # 'エンジェル・ハイロゥ', '第６０話', '最後のシ者'),
            0x74: ("[70]", self.tr("Unified"), self.tr("Stage 61"), self.tr("Fate's Arrow")),  # '共通', '第６１話', '運命の矢'),
            0x75: ("[71]", self.tr("Unified"), self.tr("Stage 62 Act 1"), self.tr("Do You Remember Love?")),  # '共通', '第６２話第１幕', '愛・おぼえていますか'),
            0x76: ("[71]", self.tr("Unified"), self.tr("Stage 62 Act 2"), self.tr("Do You Remember Love?")),  # '共通', '第６２話第２幕', '愛・おぼえていますか'),
            0x77: ("[72]", self.tr("Unified"), self.tr("Stage 64 Act 1"), self.tr("Air")),  # '共通', '第６４話第１幕', 'Air'),
            0x78: ("[72]", self.tr("Unified"), self.tr("Stage 64 Act 2"), self.tr("Air")),  # '共通', '第６４話第２幕', 'Air'),
            0x79: ("[73]", self.tr("Unified"), self.tr("Stage 65"), self.tr("The Gear Of Destiny")),  # '共通', '第６５話', 'ギア・オブ・デスティニー'),
            0x7A: ("[74]", self.tr("45 or More Points"), self.tr("Stage 66"), self.tr("The Banquet Of Despair Begins Now")),  # '熟練度４５以上', '第６６話', '絶望の宴は今から始まる'),
            0x7B: ("[75]", self.tr("45 or More Points"), self.tr("Stage 67 Act 1"), self.tr("For This Planet's Tomorrow")),  # '熟練度４５以上', '第６７話第１幕', 'この星の明日のために'),
            0x7C: ("[75]", self.tr("45 or More Points"), self.tr("Stage 67 Act 2"), self.tr("For This Planet's Tomorrow")),  # '熟練度４５以上', '第６７話第２幕', 'この星の明日のために'),
            0x7D: ("[75]", self.tr("45 or More Points"), self.tr("Stage 67 Act 3"), self.tr("For This Planet's Tomorrow")),  # '熟練度４５以上', '第６７話第３幕', 'この星の明日のために'),
            0x7E: (self.tr("Dummy"), self.tr("Dummy"), self.tr("Dummy"), self.tr("Dummy")), # "ダミー", "ダミー", "ダミー", "ダミー"
            0x7F: ("[77]", self.tr("45 or Less Points"), self.tr("Stage 66"), self.tr("No Escape For Humanity")),  # '熟練度４５未満', '第６６話', '人類に逃げ場なし'),
            0x80: ("[78]", self.tr("45 or Less Points"), self.tr("Stage 67 Act 1"), self.tr("Spirits Of Steel")),  # '熟練度４５未満', '第６７話第１幕', '鋼の魂'),
            0x81: ("[78]", self.tr("45 or Less Points"), self.tr("Stage 67 Act 2"), self.tr("Spirits Of Steel")),  # '熟練度４５未満', '第６７話第２幕', '鋼の魂'),
            0x82: (self.tr("Dummy"), self.tr("Dummy"), self.tr("Dummy"), self.tr("Dummy")), # "ダミー", "ダミー", "ダミー", "ダミー"
            0x83: (self.tr("Dummy"), self.tr("Dummy"), self.tr("Dummy"), self.tr("Dummy")), # "ダミー", "ダミー", "ダミー", "ダミー"
            0x84: (self.tr("Dummy"), self.tr("Dummy"), self.tr("Dummy"), self.tr("Dummy")), # "ダミー", "ダミー", "ダミー", "ダミー"
            0x85: (self.tr("Dummy"), self.tr("Dummy"), self.tr("Dummy"), self.tr("Dummy")), # "ダミー", "ダミー", "ダミー", "ダミー"
            0x86: ("[7C]", self.tr("Unified"), self.tr("Stage 28"), self.tr("The Island Of EOT")),  # '共通', '第２８話', 'ＥＯＴの島'),
            0x87: ("[7D]", self.tr("Super"), self.tr("Stage 29"), self.tr("Within The Soul Lies An Unseen Blade")),  # 'スーパー系', '第２９話', '心に念じる見えない刃'),
            0x88: ("[7E]", self.tr("Real"), self.tr("Stage 29"), self.tr("The Black Super Warrior")),  # 'リアル系', '第２９話', '黒い超闘士'),
            0x89: ("[7F]", self.tr("Unified"), self.tr("Stage 48"), self.tr("For Whom The Bell Tolls")),  # '共通', '第４８話', '誰がために鐘は鳴る'),
            0x8A: ("[80]", self.tr("Unified"), self.tr("Stage 49"), self.tr("The Path Of Hope, The Path Of Despair")),  # '共通', '第４９話', '進路に光明、退路に絶望'),
            0x8B: ("[81]", self.tr("Brute Force"), self.tr("Stage 30"), self.tr("Spirit Possession")),  # '力ずくで撃退', '第３０話', '精霊憑依'),
        }
